### ISSUE TITLE
Should not silently fail on parse error

### ISSUE THREAD

**Issue by pongloongyeat** [wutsi/sdui#15]
Was playing around with the `sdui` package and used a `StaticRouteContentProvider` with the following json:

```json
{
  "type": "Screen",
  "appBar": {
    "type": "AppBar",
    "attributes": {
      "title": "Profile",
      "elevation": 0.0
    }
  },
  "child": {
    "type": "ListView",
    "attributes": {
      "shrinkWrap": true
    },
    "children": [
      {
        "type": "Text",
        "attributes":  {
          "caption": "NameA"
        }
      },
      {
        "type": "Text",
        "caption": "NameB"
      }
    ]
  }
}
```

NameB does not render (which is expected since the "captions" property isn't in a Map in "attributes") and should not fail silently. A simple warning in console would also suffice.

**Comment by wutsi** [comment]
@pongloongyeat added a log when `attributes` element not found
