### ISSUE TITLE
feature request: extending supported widgets

### ISSUE THREAD

**Issue by Lerado** [wutsi/sdui#18]
It would be great to have a way to extend the current set of widgets classes by defining our own SDUIWidget classes and add it programmatically to the set of supported ones. It also helps to have more control over what is rendered in the outcome.

**Comment by wutsi** [comment]
I have it in plan...
Will be added soon

**Comment by wutsi** [comment]
@Lerado get the latest version - extension support has been added.
See README file to lean how to use it
