### ISSUE TITLE
Move all related 3rd party dependencies and widgets to another package

### ISSUE THREAD

**Issue by RodolfoSilva** [wutsi/sdui#23]
Hey @wutsi, thanks for providing this awesome library.
I have a suggestion, could we move all related 3rd party dependencies and widgets to another package?
And have something like this:

- sdui_core OR sdui - With all the essentials that are really needed to get started with sdui
- sdui_plus - With all other packages and extra widgets (carousel, cached_network_image, file_picker, image_picker, qr_code_scanner, qr_flutter...)

What do you think?

**Comment by wutsi** [comment]
yeah, this is a good idea actually
do you want to help splitting the project?

**Comment by RodolfoSilva** [comment]
Yeah, I could help you. You want keep in a monorepo or move the 3rd party to a new one?

**Comment by wutsi** [comment]
lets move to new repo for the `sdui_plus` and we will cleanup the main `sdui` after.
I currently have projects that depends on `sdui`

**Comment by RodolfoSilva** [comment]
Ok, how can we proceed?
