### ISSUE TITLE
How to use sdui package on web

### ISSUE THREAD

**Issue by MatheusMariano** [wutsi/sdui#73]
Hello, I'm trying to use this package on the web for job proposals, but I'm having a really hard time getting it done. Is there any way I can try to achieve this?

**Comment by wutsi** [comment]
I've never test it with web based project

**Comment by MatheusMariano** [comment]
When I try to run the project on the web, these two errors appear in the browser console:

SyntaxError not caught: unexpected token 'null' wrap.dart.lib.js:169
TypeError not caught: Unable to read properties of undefined (reading 'src__route') in load__packages__nasajon_sdui__shared__widgets__sdui__sdui_component_notifier_dart (sdui_component_notifier.dart.lib.js:53:50)

Looking at this second I found that this happens in the route widget: Uncaught TypeError: Cannot read properties of undefined (reading 'src__route')

Any idea?
